version: "3.8"
services:
  crawl4ai-rag:
    image: mcp/crawl4ai-rag:latest           # можно собрать сами, см. ниже
    build:
      context: ./mcp-crawl4ai-rag
      args:
        PORT: 8051
    env_file:
      - .env
    ports:
      - "8051:8051"
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G


networks:
  dokploy-network:
    external: true
