services:
  crawl4ai-rag:
    build:    
      context: . 
      dockerfile: Dockerfile
      args:
        PORT: 8051   
    image: crawl4ai-rag:local
    env_file:
      - .env   
    environment:  
      TRANSPORT: "sse"   
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_BASE_URL: "${OPENAI_BASE_URL}"
      # режем всё «лишнее»
      USE_CONTEXTUAL_EMBEDDINGS: "false"
      USE_HYBRID_SEARCH: "false"
      USE_AGENTIC_RAG: "false"
      USE_RERANKING: "false"
      USE_KNOWLEDGE_GRAPH: "false"
    ports:
      - "8051:8051"
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

networks:
  dokploy-network:
    external: true 
